export enum CategoryChoice{
    SHOWALLCATEGORY = 1,
    CREATECATEGORY = 2,
    UPDATECATEGORY = 3,
    REMOVECATEGORY = 4,
    SHOWPRODUCTBYCATEGORY = 5
}

export enum ProductChoice{
    SHOWALLPRODUCT = 1,
    CREATEPRODUCT = 2,
    UPDATEPRODUCT = 3,
    REMOVEPRODUCT = 4,
    SEARCHPRODUCTBYNAME = 5,
    SORTBYPRICE = 6,
    ADDPRODUCTTOCATEGORY = 7
}
