export enum ChoiceMenuUser{
    SHOWALLPRODUCT = 1,
    FILTERPRODUCTSBYPRICE = 2,
    SEARCHPRODUCTSBYNAME = 3,
    SORTPRODUCTSBYPRICE = 4,
    CART = 5,
    SHOWNUMBEROFPRODUCTSBYCATEGORY = 6,
    SHOWHOSTSELLINGPRODUCT = 7
}

export enum ChoiceSort{
    SORTUP = 1,
    SORTDOWN = 2
}

export enum ChoiceCart{
    SHOWALLPRODUCTINCART = 1,
    UPDATEAMOUNT = 2,
    REMOVEPRODUCTFROMCART = 3,
    PAY = 4
}